name: Cron check

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cron_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: data.json
          key: data-${{ runner.os }}-${{ github.run_id }}
          restore-keys: data-${{ runner.os }}
      - name: Install dependencies
        run: python -m pip install --break-system-packages python-dotenv requests
      - name: run
        run: python checker.py
        env: # Or as an environment variable
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          SECRET_LOGIN: ${{ secrets.SECRET_LOGIN }}
