name: Cron check

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

jobs:
  cron_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: data.json
      - name: Install dependencies
        run: pip install python-dotenv requests
      - name: run
        run: python checker.py
        env: # Or as an environment variable
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          COOKIE: ${{ secrets.COOKIE }}
