name: Cron check

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cron_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: data.json
          key: ${{ runner.os }}-primes
      - name: Install dependencies
        run: pip install python-dotenv requests
      - name: run
        run: python checker.py
        env: # Or as an environment variable
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          SECRET_LOGIN: ${{ secrets.SECRET_LOGIN }}
      - uses: actions/cache/save@v4
        id: cache-save
        if: always() # always save cache
        with:
          path: data.json
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
